workflows:
  android-app: # workflow ID
    name: Android app # workflow name
    scripts:
      - ./gradlew assembleDebug
    artifacts:
      - app/build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - devbizsolution@gmail.com