workflows:
  native-android:
    name: Native Android
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.davit.encrypefilesecurity"
    scripts:
      - name: Build Android debug
        script: ./gradlew bundleDebug
    artifacts:
      - android/app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - devbizsolution@gmail.com
        notify:
          success: true
          failure: false